### ISSUE TITLE
Unable to build openjdk 9,10 packages.

### ISSUE THREAD

**Issue by vaikas** [wolfi-dev/os#18667]
As part of cleaning up the jmods provides here:
https://github.com/wolfi-dev/os/pull/18629

Noticed that I was unable to build some older versions of java with identical error like this (for openjdk-9, and openjdk-10):

```
Building target 'images' in configuration 'linux-aarch64-normal-server-release'
Warning: No mercurial configuration present and no .src-rev
Compiling 3 files for COMPILE_CREATE_SYMBOLS
Compiling 100 properties into resource bundles for java.desktop
Error: time is more than 10 years from present: 1388527200000
java.lang.RuntimeException: time is more than 10 years from present: 1388527200000
	at build.tools.generatecurrencydata.GenerateCurrencyData.makeSpecialCaseEntry(GenerateCurrencyData.java:288)
	at build.tools.generatecurrencydata.GenerateCurrencyData.buildMainAndSpecialCaseTables(GenerateCurrencyData.java:227)
	at build.tools.generatecurrencydata.GenerateCurrencyData.main(GenerateCurrencyData.java:158)
```

This happens with both 9, 10.

Which led me to here:
https://issues.guix.gnu.org/68333

And I am just wondering since there seems to be a patch floating around somewhere, was hoping to see if there's just a newer version of the sources, but can't seem to find it. I poked around here a bit:
https://hg.openjdk.org/jdk9

Anyways, this is a tracking bug for fixing 9,10.

**Comment by sergiodj** [comment]
I believe this has been fixed, so I'm closing the bug.
