### ISSUE TITLE
FTBFS: jack

### ISSUE THREAD

**Issue by imjasonh** [wolfi-dev/os#23358]
```
2024-07-06 20:53:13 (5.10 MB/s) - 'jack2-v1.9.22.tar.gz' saved [933448]

jack2-v1.9.22.tar.gz: OK
/home/build/waflib/Utils.py:733: SyntaxWarning: invalid escape sequence '\d'
  return re.split('\d+$', s)[0]
/home/build/waflib/ConfigSet.py:14: SyntaxWarning: invalid escape sequence '\ '
  re_imp = re.compile('^(#)*?([^#=]*?)\ =\ (.*?)$', re.M)
/home/build/waflib/ansiterm.py:267: SyntaxWarning: invalid escape sequence '\['
  ansi_tokens = re.compile('(?:\x1b\[([0-9?;]*)([a-zA-Z])|([^\x1b]+))')
/home/build/waflib/Context.py:610: SyntaxWarning: invalid escape sequence '\_'
  """
Traceback (most recent call last):
  File "/home/build/./waf", line 166, in <module>
    from waflib import Scripting
  File "/home/build/waflib/Scripting.py", line 10, in <module>
    from waflib import Utils, Configure, Logs, Options, ConfigSet, Context, Errors, Build, Node
  File "/home/build/waflib/Configure.py", line 16, in <module>
    from waflib import ConfigSet, Utils, Options, Logs, Context, Build, Errors
  File "/home/build/waflib/Options.py", line 14, in <module>
    from waflib import Logs, Utils, Context, Errors
  File "/home/build/waflib/Context.py", line 9, in <module>
    import os, re, imp, sys
ModuleNotFoundError: No module named 'imp'
```

https://cloudlogging.app.goo.gl/xPppu7ZNhGWsieCv8

**Comment by justinvreeland** [comment]
imp was deprecated in python3.11 and this is trying to build with python2.12.

```
Python 3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import imp
<stdin>:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
```

There's a fix on the jack12 develop branch that hasn't been included in a release yet though:

https://github.com/jackaudio/jack2/commit/250420381b1a6974798939ad7104ab1a4b9a9994
