### ISSUE TITLE
py3-sphinx missing its dependencies

### ISSUE THREAD

**Issue by pnasrat** [wolfi-dev/os#26703]
```
77d032b47a79:/work/packages# apk add py3-sphinx
77d032b47a79:/work/packages# sphinx-build --version
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/lib/python3.12/site-packages/sphinx/cmd/build.py", line 17, in <module>
    from docutils.utils import SystemMessage
ModuleNotFoundError: No module named 'docutils'
```

**Comment by pnasrat** [comment]
I think this is due to the fact the sphinxcontrib are set to depend on sphinx

```
2024/08/20 11:15:43 ERRO unresolvable cycle: py3-sphinxcontrib-applehelp:2.0.0-r0@local -> py3-sphinx:8.0.2-r1@local, caused by: py3-sphinx:8.0.2-r1@local -> py3-sphinxcontrib-applehelp:2.0.0-r0@local
2024/08/20 11:15:43 ERRO unresolvable cycle: py3-sphinxcontrib-devhelp:2.0.0-r0@local -> py3-sphinx:8.0.2-r1@local, caused by: py3-sphinx:8.0.2-r1@local -> py3-sphinxcontrib-devhelp:2.0.0-r0@local
2024/08/20 11:15:43 ERRO unresolvable cycle: py3-sphinxcontrib-htmlhelp:2.1.0-r0@local -> py3-sphinx:8.0.2-r1@local, caused by: py3-sphinx:8.0.2-r1@local -> py3-sphinxcontrib-htmlhelp:2.1.0-r0@local
2024/08/20 11:15:43 ERRO unresolvable cycle: py3-sphinxcontrib-qthelp:2.0.0-r0@local -> py3-sphinx:8.0.2-r1@local, caused by: py3-sphinx:8.0.2-r1@local -> py3-sphinxcontrib-qthelp:2.0.0-r0@local
2024/08/20 11:15:43 ERRO unresolvable cycle: py3-sphinxcontrib-serializinghtml:2.0.0-r0@local -> py3-sphinx:8.0.2-r1@local, caused by: py3-sphinx:8.0.2-r1@local -> py3-sphinxcontrib-serializinghtml:2.0.0-r0@local
```

**Comment by pnasrat** [comment]
pypi deps do not require sphinx from the core plugins my PR does this also

```
 ~/scratch/sphinx-deps $ pip install --dry-run --report r.json sphinxcontrib-applehelp sphinxcontrib-devhelp sphinxcontrib-htmlhelp sphinxcontrib-jsmath sphinxcontrib-qthelp sphinxcontrib-serializinghtml
Collecting sphinxcontrib-applehelp
  Using cached sphinxcontrib_applehelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-devhelp
  Using cached sphinxcontrib_devhelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-htmlhelp
  Using cached sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-jsmath
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting sphinxcontrib-qthelp
  Using cached sphinxcontrib_qthelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-serializinghtml
  Using cached sphinxcontrib_serializinghtml-2.0.0-py3-none-any.whl.metadata (2.4 kB)
Using cached sphinxcontrib_applehelp-2.0.0-py3-none-any.whl (119 kB)
Using cached sphinxcontrib_devhelp-2.0.0-py3-none-any.whl (82 kB)
Using cached sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl (98 kB)
Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Using cached sphinxcontrib_qthelp-2.0.0-py3-none-any.whl (88 kB)
Using cached sphinxcontrib_serializinghtml-2.0.0-py3-none-any.whl (92 kB)
Would install sphinxcontrib-applehelp-2.0.0 sphinxcontrib-devhelp-2.0.0 sphinxcontrib-htmlhelp-2.1.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-2.0.0 sphinxcontrib-serializinghtml-2.0.0
```
