### ISSUE TITLE
broken package: trino 453-r2,3

### ISSUE THREAD

**Issue by tuananh** [wolfi-dev/os#30762]
ref: https://github.com/wolfi-dev/os/pull/27776#issuecomment-2410528088

`453-r1` works but `453-r2` and `453-r3` doesn't.

im getting this error when booting trino in r2& r3

maybe we need to add a test for this to catch it in future update.

```
2024-10-14T08:37:48.171Z	INFO	main	Bootstrap	optimizer.use-exact-partitioning                                                        false                                                                      false                                                                      When enabled this forces data repartitioning unless the partitioning of upstream stage matches exactly what downstream stage expects
2024-10-14T08:37:48.171Z	INFO	main	Bootstrap	optimizer.use-legacy-window-filter-pushdown                                             false                                                                      false
2024-10-14T08:37:48.171Z	INFO	main	Bootstrap	use-preferred-write-partitioning                                                        true                                                                       true
2024-10-14T08:37:48.171Z	INFO	main	Bootstrap	optimizer.use-table-scan-node-partitioning                                              true                                                                       true                                                                       Adapt plan to node pre-partitioned tables
2024-10-14T08:37:48.171Z	INFO	main	Bootstrap	transaction.idle-check-interval                                                         1.00m                                                                      1.00m                                                                      Time interval between idle transactions checks
2024-10-14T08:37:48.171Z	INFO	main	Bootstrap	transaction.idle-timeout                                                                5.00m                                                                      5.00m                                                                      Amount of time before an inactive transaction is considered expired
2024-10-14T08:37:48.171Z	INFO	main	Bootstrap	transaction.max-finishing-concurrency                                                   1                                                                          1                                                                          Maximum parallelism for committing or aborting a transaction
2024-10-14T08:37:50.694Z	ERROR	main	io.trino.server.Server	ch/qos/logback/core/rolling/SizeAndTimeBasedFNATP
java.lang.NoClassDefFoundError: ch/qos/logback/core/rolling/SizeAndTimeBasedFNATP
	at io.airlift.http.server.DelimitedRequestLog.<init>(DelimitedRequestLog.java:74)
	at io.airlift.http.server.HttpServer.createDelimitedRequestLog(HttpServer.java:500)
	at io.airlift.http.server.HttpServer.<init>(HttpServer.java:348)
	at io.airlift.http.server.HttpServerProvider.get(HttpServerProvider.java:158)
	at io.airlift.http.server.HttpServerProvider.get(HttpServerProvider.java:46)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:67)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:53)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:62)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:59)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:264)
	at io.trino.server.Server.doStart(Server.java:141)
	at io.trino.server.Server.lambda$start$0(Server.java:93)
	at io.trino.$gen.Trino_453_dirty____20241014_083746_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:93)
	at io.trino.server.TrinoServer.main(TrinoServer.java:37)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 27 more

```

**Comment by tuananh** [comment]
cc @hectorj2f

**Comment by tuananh** [comment]
> Could you share some details on how you reproduce it the error ?

I just built the image and then run it with `docker run -it --rm <image>`

**Comment by tuananh** [comment]
seems to be fixed by `462-r0` in https://github.com/wolfi-dev/os/pull/30986/files
