### ISSUE TITLE
harfbuzz fails to build on amd64

### ISSUE THREAD

**Issue by murraybd** [wolfi-dev/os#37366]
The package harfbuzz fails to build from source with the following error:

```
[181/343] Generating src/harfbuzz-gobject.def with a custom command
[182/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-shaper-khmer.cc.o
[183/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-shaper-indic.cc.o
[184/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-shaper-indic-table.cc.o
[185/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-shaper-hebrew.cc.o
[186/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-shaper-hangul.cc.o
[187/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-shaper-default.cc.o
[188/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-shaper-arabic.cc.o
[189/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-name.cc.o
[190/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-metrics.cc.o
[191/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-meta.cc.o
[192/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-math.cc.o
[193/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-map.cc.o
[194/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-layout.cc.o
[195/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/OT_Var_VARC_VARC.cc.o
[196/343] Linking static target src/libharfbuzz-icu.a
[197/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-outline.cc.o
[198/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-font.cc.o
[199/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-face.cc.o
[200/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-color.cc.o
[201/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-cff2-table.cc.o
[202/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-ot-cff1-table.cc.o
[203/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-number.cc.o
[204/343] Generating src/hb-gobject-enums.cc with a custom command
[205/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-map.cc.o
[206/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-font.cc.o
[207/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-fallback-shape.cc.o
[208/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-face-builder.cc.o
[209/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-face.cc.o
[210/343] Compiling C++ object src/libharfbuzz-gobject.so.0.61010.0.p/meson-generated_.._hb-gobject-enums.cc.o
[211/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-paint-extents.cc.o
[212/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-paint.cc.o
[213/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-draw.cc.o
[214/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-common.cc.o
[215/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-buffer.cc.o
[216/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-buffer-verify.cc.o
[217/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-buffer-serialize.cc.o
[218/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-blob.cc.o
[219/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-aat-map.cc.o
[220/343] Compiling C++ object src/libharfbuzz.so.0.61010.0.p/hb-aat-layout.cc.o
[221/343] Compiling C++ object src/test-algs.p/hb-static.cc.o
[222/343] Compiling C++ object src/test-algs.p/test-algs.cc.o
[223/343] Linking static target src/libharfbuzz-gobject.a
[224/343] Linking static target src/libharfbuzz-cairo.a
[225/343] Linking static target src/libharfbuzz.a
[226/343] Linking target src/libharfbuzz.so.0.61010.0
[227/343] Generating symbol file src/libharfbuzz.so.0.61010.0.p/libharfbuzz.so.0.61010.0.symbols
[228/343] Linking target test/threads/hb-shape-threads
[229/343] Linking target util/hb-ot-shape-closure
[230/343] Linking target util/hb-shape
[231/343] Linking target src/libharfbuzz-gobject.so.0.61010.0
[232/343] Linking target src/libharfbuzz-icu.so.0.61010.0
[233/343] Linking target src/test-unicode-ranges
[234/343] Linking target src/test-item-varstore
[235/343] Linking target src/test-tuple-varstore
[236/343] Linking target src/test-priority-queue
[237/343] Linking target src/test-instancer-solver
[238/343] Linking target src/test-repacker
[239/343] Linking target src/test-vector
[240/343] Linking target src/test-serialize
[241/343] Linking target src/test-set
[242/343] Linking target src/test-ot-tag
[243/343] Linking target src/test-number
[244/343] Linking target src/test-multimap
[245/343] Linking target src/test-map
[246/343] Linking target src/test-machinery
[247/343] Linking target src/test-iter
[248/343] Linking target src/test-classdef-graph
[249/343] Linking target src/test-cff
[250/343] Linking target src/test-bimap
[251/343] Linking target src/test-array
[252/343] Linking target src/test-algs
[253/343] Linking target src/test-use-table
[254/343] Linking target src/test-ot-gsub-would-substitute
[255/343] Linking target src/test-ot-gsub-get-alternates
[256/343] Linking target src/test-ot-gpos-size-params
[257/343] Linking target src/test-ot-glyphname
[258/343] Linking target src/test-ot-name
[259/343] Linking target src/test-ot-meta
[260/343] Linking target src/test-buffer-serialize
[261/343] Linking target src/test-basics
[262/343] Linking target src/main
[263/343] Linking target src/libharfbuzz-cairo.so.0.61010.0
[264/343] Generating src/HarfBuzz-0.0.gir with a custom command (wrapped by meson to set env)
[265/343] Generating symbol file src/libharfbuzz-gobject.so.0.61010.0.p/libharfbuzz-gobject.so.0.61010.0.symbols
[266/343] Generating symbol file src/libharfbuzz-icu.so.0.61010.0.p/libharfbuzz-icu.so.0.61010.0.symbols
ninja: job failed: env PKG_CONFIG_PATH=/home/build/output/meson-uninstalled PKG_CONFIG=/usr/bin/pkg-config CC=cc /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=HarfBuzz --nsversion=0.0 --warn-all --output src/HarfBuzz-0.0.gir --c-include=hb-gobject.h --cflags-begin -DHB_NO_SINGLE_HEADER_ERROR -DHAVE_GOBJECT -DHB_EXTERN= --cflags-end -I/home/build/src -I/home/build/output/src -I/home/build/. -I/home/build/output/. --filelist=/home/build/output/src/libharfbuzz-gobject.so.0.61010.0.p/HarfBuzz_0.0_gir_filelist --include=GObject-2.0 --include=freetype2-2.0 --symbol-prefix=hb --symbol-prefix=hb_gobject --identifier-prefix=hb_ --pkg-export=harfbuzz-gobject --pkg-export=harfbuzz --cflags-begin -DHAVE_CONFIG_H -DHAVE_CONFIG_H -I/home/build/. -I/home/build/output/. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/home/build/src/. -I/home/build/output/src/. -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/home/build/output/src -lharfbuzz -L/home/build/output/src --library harfbuzz-gobject -L/home/build/output/src -L/home/build/output/src --library harfbuzz -lglib-2.0 -lgobject-2.0 -lm -lfreetype -lgraphite2 -lgirepository-1.0
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 99, in <module>
    from giscanner.utils import dll_dirs
  File "/usr/lib/gobject-introspection/giscanner/utils.py", line 385, in <module>
    import distutils.cygwinccompiler
ModuleNotFoundError: No module named 'distutils'
ninja: subcommand failed
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/build/output -j 96
deleting guest dir /tmp/melange-guest-2642873477
deleting workspace dir /tmp/melange-workspace-349333325
removing image path /tmp/melange-guest-1180161835
failed to build package: unable to run package harfbuzz pipeline: unable to run pipeline: unable to run pipeline: exit status 1
```

**Comment by murraybd** [comment]
This is still failing but in a different fashion now and the meson log contains:

```
Command line: `c++ -I/usr/include/freetype2 -I/usr/include/libpng16 /home/build/output/meson-private/tmpx940fi5r/testfile.cpp -o /home/build/output/meson-private/tmpx9
40fi5r/output.exe -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -std=c++17 -fno-exceptions /usr/lib/libfreetype.so` -> 0
Checking for function "FT_Get_Transform" with dependency freetype2: YES 
Program gen-hb-version.py found: YES (/home/build/src/gen-hb-version.py)
Configuring hb-version.h with command
Running command: /home/build/src/gen-hb-version.py 10.1.0 /home/build/output/src/hb-version.h /home/build/src/hb-version.h.in
--- stdout ---

--- stderr ---
env: can't execute 'python3': No such file or directory



src/meson.build:3:15: ERROR: Command `/home/build/src/gen-hb-version.py 10.1.0 /home/build/output/src/hb-version.h /home/build/src/hb-version.h.in` failed with status 
127.
```

**Comment by murraybd** [comment]
This was fixed by 2bd355a57c
