### ISSUE TITLE
libsecret fails to build on amd64

### ISSUE THREAD

**Issue by murraybd** [wolfi-dev/os#37362]
The package libsecret fails to build from source with the following error:

```
[47/146] Building translation po/en_GB/LC_MESSAGES/libsecret-en_GB.mo
[48/146] Building translation po/el/LC_MESSAGES/libsecret-el.mo
[49/146] Building translation po/de/LC_MESSAGES/libsecret-de.mo
[50/146] Building translation po/da/LC_MESSAGES/libsecret-da.mo
[51/146] Building translation po/cs/LC_MESSAGES/libsecret-cs.mo
[52/146] Building translation po/ckb/LC_MESSAGES/libsecret-ckb.mo
[53/146] Building translation po/ca@valencia/LC_MESSAGES/libsecret-ca@valencia.mo
[54/146] Building translation po/ca/LC_MESSAGES/libsecret-ca.mo
[55/146] Building translation po/bs/LC_MESSAGES/libsecret-bs.mo
[56/146] Building translation po/bg/LC_MESSAGES/libsecret-bg.mo
[57/146] Building translation po/be/LC_MESSAGES/libsecret-be.mo
[58/146] Building translation po/as/LC_MESSAGES/libsecret-as.mo
[59/146] Building translation po/ar/LC_MESSAGES/libsecret-ar.mo
[60/146] Building translation po/an/LC_MESSAGES/libsecret-an.mo
[61/146] Building translation po/ab/LC_MESSAGES/libsecret-ab.mo
[62/146] Compiling C object libsecret/test-file-collection.p/test-file-collection.c.o
[63/146] Compiling C object libsecret/test-collection.p/test-collection.c.o
[64/146] Compiling C object libsecret/test-item.p/test-item.c.o
[65/146] Compiling C object libsecret/test-password.p/test-password.c.o
[66/146] Compiling C object libsecret/test-methods.p/test-methods.c.o
[67/146] Compiling C object libsecret/test-paths.p/test-paths.c.o
[68/146] Compiling C object libsecret/test-session.p/test-session.c.o
[69/146] Compiling C object libsecret/test-service.p/test-service.c.o
[70/146] Compiling C object libsecret/test-prompt.p/test-prompt.c.o
[71/146] Compiling C object libsecret/test-value.p/test-value.c.o
[72/146] Generating GObject enum file libsecret/secret-enum-types.h (wrapped by meson to capture output)
[73/146] Generating gdbus header libsecret/secret-dbus-generated.h
[74/146] Generating gdbus source libsecret/secret-dbus-generated.c
[75/146] Compiling C object libsecret/libmock-service.so.p/mock-service.c.o
[76/146] Compiling C object libsecret/test-attributes.p/test-attributes.c.o
[77/146] Compiling C object egg/test-hkdf.p/test-hkdf.c.o
[78/146] Compiling C object egg/test-dh.p/test-dh.c.o
[79/146] Compiling C object egg/test-secmem.p/test-secmem.c.o
[80/146] Compiling C object egg/libegg.a.p/egg-libgcrypt.c.o
[81/146] Compiling C object egg/libegg.a.p/egg-keyring1-libgcrypt.c.o
[82/146] Compiling C object egg/libegg.a.p/egg-hkdf-libgcrypt.c.o
[83/146] Compiling C object egg/libegg.a.p/egg-dh-libgcrypt.c.o
[84/146] Compiling C object egg/libegg.a.p/egg-dh.c.o
[85/146] Compiling C object egg/libegg.a.p/egg-testing.c.o
[86/146] Compiling C object egg/libegg.a.p/egg-buffer.c.o
[87/146] Compiling C object egg/libegg.a.p/egg-unix-credentials.c.o
[88/146] Compiling C object egg/libegg.a.p/egg-secure-memory.c.o
[89/146] Compiling C object egg/libegg.a.p/egg-hex.c.o
[90/146] Compiling C object egg/test-hex.p/test-hex.c.o
[01m[K../egg/egg-libgcrypt.c:[m[K In function '[01m[Kegg_libgcrypt_initialize[m[K':
[01m[K../egg/egg-libgcrypt.c:78:25:[m[K [01;35m[Kwarning: [m[K'[01m[Kgcry_set_log_handler[m[K' is deprecated [[01;35m[K-Wdeprecated-declarations[m[K]
   78 |                         [01;35m[Kgcry_set_log_handler[m[K (log_handler, NULL);
      |                         [01;35m[K^~~~~~~~~~~~~~~~~~~~[m[K
In file included from [01m[K../egg/egg-libgcrypt.c:31[m[K:
[01m[K/usr/include/gcrypt.h:2025:6:[m[K [01;36m[Knote: [m[Kdeclared here
 2025 | void [01;36m[Kgcry_set_log_handler[m[K (gcry_handler_log_t f,
      |      [01;36m[K^~~~~~~~~~~~~~~~~~~~[m[K
[91/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-file-item.c.o
[92/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-file-collection.c.o
[93/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-file-backend.c.o
[94/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-util.c.o
[95/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-session.c.o
[96/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-paths.c.o
[97/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-value.c.o
[98/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-service.c.o
[99/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-schemas.c.o
[100/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-schema.c.o
[101/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-retrievable.c.o
[102/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-prompt.c.o
[103/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-password.c.o
[104/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-methods.c.o
[105/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-item.c.o
[106/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-collection.c.o
[107/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-backend.c.o
[108/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/secret-attributes.c.o
[109/146] Generating GObject enum file libsecret/secret-enum-types.c (wrapped by meson to capture output)
[110/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/meson-generated_.._secret-dbus-generated.c.o
[111/146] Linking static target egg/libegg.a
[112/146] Linking target egg/test-hkdf
[113/146] Linking target egg/test-dh
[114/146] Linking target egg/test-secmem
[115/146] Linking target egg/test-hex
[116/146] Linking static target libsecret/libmock-service.a
[117/146] Linking target libsecret/libmock-service.so
[118/146] Generating libsecret/MockService-0.gir with a custom command (wrapped by meson to set env)
[119/146] Generating symbol file libsecret/libmock-service.so.p/libmock-service.so.symbols
[120/146] Compiling C object libsecret/libsecret-1.so.0.0.0.p/meson-generated_.._secret-enum-types.c.o
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 27, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 31, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
ninja: job failed: env PKG_CONFIG_PATH=/home/build/output/meson-uninstalled PKG_CONFIG=/usr/bin/pkg-config CC=cc /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=MockService --nsversion=0 --warn-all --output libsecret/MockService-0.gir --c-include=libsecret/mock-service.h -I/home/build/libsecret -I/home/build/output/libsecret -I/home/build/. -I/home/build/output/. --filelist=/home/build/output/libsecret/libmock-service.so.p/MockService_0_gir_filelist --include=GObject-2.0 --include=Gio-2.0 --pkg-export=mock-service-0 --cflags-begin -I/home/build/. -I/home/build/output/. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/home/build/output/libsecret --library mock-service -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lgirepository-1.0
ninja: subcommand failed
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/build/output -j 64
deleting guest dir /tmp/melange-guest-925652486
deleting workspace dir /tmp/melange-workspace-3029937319
removing image path /tmp/melange-guest-3511463657
failed to build package: unable to run package libsecret pipeline: unable to run pipeline: unable to run pipeline: exit status 1
```

**Comment by murraybd** [comment]
This was also fixed by commit 4780497f93 which sorted out gobject-introspection's build failure.
