### ISSUE TITLE
glib-gir fails to build on amd64

### ISSUE THREAD

**Issue by murraybd** [wolfi-dev/os#37368]
The package glib-gir fails to build from source with the following error:

```
[626/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/gconvert.c.o
[627/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/gchecksum.c.o
[628/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/gcharset.c.o
[629/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/gbytes.c.o
[630/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/gbookmarkfile.c.o
[631/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/gbitlock.c.o
[632/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/gbase64.c.o
[633/711] Linking static target gio/inotify/libinotify.a
[634/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/gbacktrace.c.o
[635/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/gatomic.c.o
[636/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/gasyncqueue.c.o
[637/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/garray.c.o
[638/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/garcbox.c.o
[639/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/deprecated_gthread-deprecated.c.o
[640/711] Compiling C object gobject/libgobject-2.0.so.0.8200.2.p/meson-generated_.._glib-enumtypes.c.o
[641/711] Compiling C object gio/libgio-2.0.so.0.8200.2.p/meson-generated_.._gioenumtypes.c.o
[642/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/deprecated_grel.c.o
[643/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/deprecated_gcompletion.c.o
[644/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/deprecated_gcache.c.o
[645/711] Compiling C object glib/libglib-2.0.so.0.8200.2.p/deprecated_gallocator.c.o
[646/711] Linking static target girepository/libgirepository-2.0.a
[647/711] Linking static target girepository/cmph/libcmph.a
In function '[01m[Kg_error_new_steal[m[K',
    inlined from '[01m[Kg_error_copy[m[K' at [01m[K../glib/gerror.c:421:10[m[K:
[01m[K../glib/gerror.c:249:19:[m[K [01;35m[Kwarning: [m[K'[01m[Kinfo.copy[m[K' may be used uninitialized [[01;35m[K-Wmaybe-uninitialized[m[K]
  249 |   GError *error = [01;35m[Kg_error_allocate (domain, &info)[m[K;
      |                   [01;35m[K^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m[K
[01m[K../glib/gerror.c:[m[K In function '[01m[Kg_error_copy[m[K':
[01m[K../glib/gerror.c:413:19:[m[K [01;36m[Knote: [m[K'[01m[Kinfo.copy[m[K' was declared here
  413 |   ErrorDomainInfo [01;36m[Kinfo[m[K;
      |                   [01;36m[K^~~~[m[K
[648/711] Linking static target glib/libglib-2.0.a
[649/711] Linking target glib/libglib-2.0.so.0.8200.2
[650/711] Generating symbol file glib/libglib-2.0.so.0.8200.2.p/libglib-2.0.so.0.8200.2.symbols
[651/711] Linking target gmodule/libgmodule-2.0.so.0.8200.2
[652/711] Linking target gthread/libgthread-2.0.so.0.8200.2
[653/711] Linking target glib/gtester
[654/711] Generating symbol file gmodule/libgmodule-2.0.so.0.8200.2.p/libgmodule-2.0.so.0.8200.2.symbols
[655/711] Linking static target gobject/libgobject-2.0.a
[656/711] Linking target gobject/libgobject-2.0.so.0.8200.2
[657/711] Generating symbol file gobject/libgobject-2.0.so.0.8200.2.p/libgobject-2.0.so.0.8200.2.symbols
[658/711] Linking target gobject/gobject-query
[659/711] Linking static target gio/libgio-2.0.a
[660/711] Linking target gio/libgio-2.0.so.0.8200.2
[661/711] Generating symbol file gio/libgio-2.0.so.0.8200.2.p/libgio-2.0.so.0.8200.2.symbols
[662/711] Linking target fuzzing/fuzz_variant_text
[663/711] Linking target fuzzing/fuzz_variant_binary_byteswap
[664/711] Linking target fuzzing/fuzz_variant_binary
[665/711] Linking target fuzzing/fuzz_uuid_string_is_valid
[666/711] Linking target fuzzing/fuzz_utf8_validate
[667/711] Linking target fuzzing/fuzz_utf8_normalize
[668/711] Linking target fuzzing/fuzz_uri_parse_params
[669/711] Linking target fuzzing/fuzz_uri_parse
[670/711] Linking target fuzzing/fuzz_uri_escape
[671/711] Linking target fuzzing/fuzz_resolver
[672/711] Linking target fuzzing/fuzz_paths
[673/711] Linking target fuzzing/fuzz_network_address_parse_uri
[674/711] Linking target fuzzing/fuzz_network_address_parse
[675/711] Linking target fuzzing/fuzz_key
[676/711] Linking target fuzzing/fuzz_inet_socket_address_new_from_string
[677/711] Linking target fuzzing/fuzz_inet_address_new_from_string
[678/711] Linking target fuzzing/fuzz_inet_address_mask_new_from_string
[679/711] Linking target fuzzing/fuzz_dbus_message
[680/711] Linking target fuzzing/fuzz_date_time_new_from_iso8601
[681/711] Linking target fuzzing/fuzz_date_parse
[682/711] Linking target fuzzing/fuzz_canonicalize_filename
[683/711] Linking target fuzzing/fuzz_bookmark
[684/711] Linking target girepository/libgirepository-2.0.so.0.8200.2
[685/711] Linking target gio/gapplication
[686/711] Linking target gio/gdbus
[687/711] Linking target gio/gsettings
[688/711] Linking target gio/glib-compile-resources
[689/711] Linking target gio/glib-compile-schemas
[690/711] Linking target gio/gio-querymodules
[691/711] Linking target gio/gresource
[692/711] Linking target gio/gio
[693/711] Generating girepository/introspection/GLib-2.0.gir with a custom command (wrapped by meson to set env)
[694/711] Generating symbol file girepository/libgirepository-2.0.so.0.8200.2.p/libgirepository-2.0.so.0.8200.2.symbols
[695/711] Linking target girepository/inspector/gi-inspect-typelib
[696/711] Linking target girepository/decompiler/gi-decompile-typelib
[697/711] Linking target girepository/compiler/gi-compile-repository
[698/711] Linking target girepository/gi-dump-types
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 27, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 31, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ninja: job failed: env PKG_CONFIG_PATH=/home/build/output/meson-uninstalled PKG_CONFIG=/usr/bin/pkg-config CC=cc /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=GLib --nsversion=2.0 --warn-all --output girepository/introspection/GLib-2.0.gir --c-include=glib.h --quiet -DGLIB_COMPILATION '-DGETTEXT_PACKAGE="dummy"' --symbol-prefix=glib --library-path=/home/build/output/girepository/introspection --library=gobject-2.0 -I/home/build/girepository/introspection -I/home/build/output/girepository/introspection -I/home/build/. -I/home/build/output/. --filelist=/home/build/output/glib/libglib-2.0.so.0.8200.2.p/GLib_2.0_gir_filelist --symbol-prefix=g --identifier-prefix=G --pkg-export=glib-2.0 --cflags-begin -D_GNU_SOURCE -DG_ENABLE_DEBUG -I/home/build/. -I/home/build/output/. -I/home/build/girepository -I/home/build/output/girepository -I/home/build/glib -I/home/build/output/glib -I/home/build/gobject -I/home/build/output/gobject -I/home/build/gio -I/home/build/output/gio -I/usr/include/libmount -I/usr/include/blkid -I/home/build/gmodule -I/home/build/output/gmodule -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include --cflags-end --add-include-path=/home/build/output/girepository/introspection --add-include-path=/usr/share/gir-1.0 -L/home/build/output/girepository -L/home/build/output/glib -L/home/build/output/gobject -L/home/build/output/gmodule -L/home/build/output/gio -L/usr/lib/../lib64 -lgirepository-2.0 -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lgmodule-2.0 -L/home/build/output/glib --library glib-2.0 -latomic -lm -lpcre2-8 -L/usr/lib/../lib64 -lffi -L/lib -lz -lmount -lgirepository-1.0 -lgobject-2.0 -lglib-2.0
ModuleNotFoundError: No module named 'giscanner._giscanner'
ninja: subcommand failed
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/build/output -j 64
deleting guest dir /tmp/melange-guest-4182834782
deleting workspace dir /tmp/melange-workspace-2569521475
removing image path /tmp/melange-guest-2954836525
failed to build package: unable to run package glib-gir pipeline: unable to run pipeline: unable to run pipeline: exit status 1
```

**Comment by BHAVISHYA2005** [comment]
its due to missing Python module (giscanner._giscanner).

**Comment by murraybd** [comment]
I was able to build the package today confirming that https://github.com/wolfi-dev/os/commit/4780497f930689d30e4723027e0ccfd655e58a2a fixes the issue.
