### ISSUE TITLE
Conda package does not seem to work anymore.

### ISSUE THREAD

**Issue by vaikas** [wolfi-dev/os#4888]
I think once we switched from using miniconda install to building from source things broke.
If I try the latest package, and try to any package related commands (search for example), I get errors about missing package support.

If I change the build file to a previous version here:
https://github.com/wolfi-dev/os/commit/fe43cb874ae6b49d04e98383c746e6171ce0ab4c

And rebuild the package (which now builds 23.7.3) I can do things like:
`/opt/conda/bin/conda search`
it will work.

```
/ # /opt/conda/bin/conda -V
conda 23.7.3
/ # /opt/conda/bin/conda search | tail -3
zstd                           1.5.4      h6a09583_0  pkgs/main
zstd                           1.5.5      h6a09583_0  pkgs/main
zstd-static                    1.4.8      h7c1a80f_1  pkgs/main
```

Versus, what I see in the latest package:
```
/ # conda -V
conda 23.7.3.dev0+dirty
/ # conda search

CondaError: Conda has not been initialized.

To enable full conda functionality, please run 'conda init'.
For additional information, see 'conda init --help'.

/ # conda search
Loading channels: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/cli/main.py", line 64, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 167, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/cli/main_search.py", line 90, in execute
        SubdirData.query_all(spec, channel_urls, subdirs),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/core/subdir_data.py", line 158, in query_all
        result = tuple(
                 ^^^^^^
      File "/usr/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/core/subdir_data.py", line 143, in subdir_query
        return tuple(
               ^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/core/subdir_data.py", line 165, in query
        self.load()
      File "/usr/lib/python3.11/site-packages/conda/core/subdir_data.py", line 265, in load
        _internal_state = self._load()
                          ^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/core/subdir_data.py", line 322, in _load
        repodata, state = fetcher.fetch_latest_parsed()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 758, in fetch_latest_parsed
        parsed, state = self.fetch_latest()
                        ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 819, in fetch_latest
        cache = self.repo_cache
                ^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 798, in repo_cache
        return RepodataCache(self.cache_path_base, self.repodata_fn)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 547, in __init__
        self.cache_path_json, self.cache_path_state, repodata_fn
        ^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 554, in cache_path_json
        self.name + ("1" if context.use_only_tar_bz2 else "") + ".json",
                            ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/base/context.py", line 936, in use_only_tar_bz2
        import conda_package_handling.api
    ModuleNotFoundError: No module named 'conda_package_handling'

`$ /usr/bin/conda search`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/usr
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

     active environment : None
       user config file : /root/.condarc
 populated config files :
          conda version : 23.7.3.dev0+dirty
    conda-build version : not installed
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=aarch64
                          __glibc=2.38=0
                          __linux=5.15.49=0
                          __unix=0=0
       base environment : /usr  (read only)
      conda av data dir : /usr/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-aarch64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-aarch64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/pkgs
                          /root/.conda/pkgs
       envs directories : /root/.conda/envs
                          /usr/envs
               platform : linux-aarch64
             user-agent : conda/23.7.3.dev0+dirty requests/2.31.0 CPython/3.11.5 Linux/5.15.49-linuxkit-pr wolfi/20230201 glibc/2.38
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

This also fails if I do a `conda init` (from a new shell, or the existing one, both fail).

@wlynch looks like you did the conversion to building from source, am I holding something wrong here?

**Comment by wlynch** [comment]
It's very possible I did something wrong with https://github.com/wolfi-dev/os/pull/4397.

The main motivation was that the miniconda install was shipping its own version of python which was getting dinged by vuln scanners, so I was trying to replace it with our own python version.

My guess was in that transition, there were more packages that were bundled in that were missed (in this case `conda_package_handling`).

https://github.com/conda/conda/blob/ae409f81d189411f02801999871a313095e5f352/pyproject.toml#L25-L37 is the list of all project dependencies, but I don't think it distinguishes app dependencies vs build dependencies.

**Comment by vaikas** [comment]
Fantastic, thanks for the pointer. I'll play more!!

**Comment by rigzba21** [comment]
Looks like [conda 24.1.1 (latest release) now has `archspec` as a dependency](https://github.com/conda/conda/blob/24.1.1/pyproject.toml#L26). Here's the issue I'm running into when trying to run `docker run --rm -it cgr.dev/chainguard/conda:latest info`:
```bash
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 196, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/cli/main_info.py", line 490, in execute
        info_dict = get_info_dict()
                    ^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/deprecations.py", line 125, in inner
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/cli/main_info.py", line 271, in get_info_dict
        _supplement_index_with_system(virtual_pkg_index)
      File "/usr/lib/python3.12/site-packages/conda/core/index.py", line 177, in _supplement_index_with_system
        for package in context.plugin_manager.get_virtual_packages():
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/plugins/manager.py", line 324, in get_virtual_packages
        return tuple(self.get_hook_results("virtual_packages"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/plugins/manager.py", line 201, in get_hook_results
        plugins = [item for items in hook() for item in items]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/plugins/virtual_packages/archspec.py", line 13, in conda_virtual_packages
        archspec_name = get_archspec_name()
                        ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/core/index.py", line 202, in get_archspec_name
        import archspec.cpu
    ModuleNotFoundError: No module named 'archspec'

`$ /usr/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

**Comment by ajayk** [comment]
@rigzba21 can you please open a new Issue
