### ISSUE TITLE
py3 sqlite3 module broken

### ISSUE THREAD

**Issue by andros21** [wolfi-dev/os#516]
Hi, it seems that `sqlite3` module doesn't work properly for both new variants [chainguard-images/python](https://github.com/chainguard-images/images/tree/main/images/python) available

### steps to reproduce

```console
$ podman run --pull always --rm -it cgr.dev/chainguard/python:latest python
Trying to pull cgr.dev/chainguard/python:latest...
Getting image source signatures
Copying blob 1b44cf38bce8 skipped: already exists
Copying config e7d64953c8 done
Writing manifest to image destination
Storing signatures
Python 3.11.1 (main, Jan  1 1970, 00:00:00) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

### some feedbacks

From build log relative to commit https://github.com/wolfi-dev/os/commit/d9a27c962992d8f7cae849f485a03d0c1cc5c9b8 during python3 `./configure` 

```console
2023-01-28T02:07:24.3723812Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for LIBSQLITE3... yes
2023-01-28T02:07:24.4141281Z 2023/01/28 02:07:24 melange (python3/x86_64): checking sqlite3.h usability... yes
2023-01-28T02:07:24.4273190Z 2023/01/28 02:07:24 melange (python3/x86_64): checking sqlite3.h presence... yes
2023-01-28T02:07:24.4273664Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3.h... yes
2023-01-28T02:07:24.5099067Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3_bind_double in -lsqlite3... no
2023-01-28T02:07:24.5642524Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3_column_decltype in -lsqlite3... no
2023-01-28T02:07:24.6206648Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3_column_double in -lsqlite3... no
2023-01-28T02:07:24.6758472Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3_complete in -lsqlite3... no
2023-01-28T02:07:24.7314337Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3_enable_shared_cache in -lsqlite3... no
2023-01-28T02:07:24.7873187Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3_progress_handler in -lsqlite3... no
2023-01-28T02:07:24.8405633Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3_result_double in -lsqlite3... no
2023-01-28T02:07:24.8922784Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3_set_authorizer in -lsqlite3... no
2023-01-28T02:07:24.9462918Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3_trace_v2 in -lsqlite3... no
2023-01-28T02:07:24.9998660Z 2023/01/28 02:07:24 melange (python3/x86_64): checking for sqlite3_trace in -lsqlite3... no
2023-01-28T02:07:25.0544294Z 2023/01/28 02:07:25 melange (python3/x86_64): checking for sqlite3_value_double in -lsqlite3... no
2023-01-28T02:07:25.1113163Z 2023/01/28 02:07:25 melange (python3/x86_64): checking for sqlite3_load_extension in -lsqlite3... no
2023-01-28T02:07:25.1659504Z 2023/01/28 02:07:25 melange (python3/x86_64): checking for sqlite3_serialize in -lsqlite3... no
2023-01-28T02:07:25.1668991Z 2023/01/28 02:07:25 melange (python3/x86_64): checking for --enable-loadable-sqlite-extensions... n/a
2023-01-28T02:07:25.1669623Z 2023/01/28 02:07:25 melange (python3/x86_64): configure: WARNING: Your version of SQLite does not support loadable extensions
```

Making a rapid comparison between `sqlite` package shipped within `wolfi-base:latest` or `alpine-base:latest`, `.dbconfig` return same output (**load_extension on**). But on alpine `sqlite3` python3 module works fine.

```console
sqlite> .dbconfig
          defensive off
            dqs_ddl on
            dqs_dml on
        enable_fkey off
        enable_qpsg off
     enable_trigger on
        enable_view on
     fts3_tokenizer off
 legacy_alter_table off
 legacy_file_format off
     load_extension on
   no_ckpt_on_close off
     reset_database off
        trigger_eqp off
     trusted_schema on
    writable_schema off
```

Thank you in advance for your support

**Comment by unzld** [comment]
@kaniini @imjasonh I'm still getting this error. Am I missing something?

```
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - sqlite-dev
    - linux-pam-dev
    - ca-certificates-bundle
    - python-3.10
    - wolfi-baselayout
    - busybox

paths:
  - path: /app
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

archs:
- x86_64
```
